Support <-debouncer.Done()
vnteamopen/godebouncer pull request #21
Opened 2022-05-10 10:53 UTC by huyvohcmc

2022-05-10 17:04 UTC, ledongthuc requested changes
A few small comments + please remember to update the example on the landing page https://godebouncer.vnteamopen.com/

2022-05-10 17:04 UTC, ledongthuc commented on README.md
> +wait := 1 * time.Second
We don't need `wait` variable anymore

2022-05-10 17:04 UTC, ledongthuc commented on debouncer.go
> +	done          chan bool
anh suggest chuyển qua dùng chan struct{} nha. struct{} đỡ tốn bộ nhớ hơn nhưng cùng mục đích

2022-05-11 06:42 UTC, rnvo requested changes

2022-05-11 06:42 UTC, rnvo commented on README.md
> +debouncer := godebouncer.new(1 * time.Second).WithTriggered(func() {
```suggestion
debouncer := godebouncer.New(1 * time.Second).WithTriggered(func() {
```
pls remove **wait** var in **main** as well 😄

2022-05-11 06:42 UTC, rnvo commented on debouncer.go
> +	return &Debouncer{timeDuration: duration, triggeredFunc: func() {}, done: make(chan struct{}, 1)}
```suggestion
	return &Debouncer{timeDuration: duration, triggeredFunc: func() {}, done: make(chan struct{})}
```

2022-05-11 06:42 UTC, rnvo commented on debouncer_test.go
> +	fmt.Println("debouncer has done signalling")
```suggestion
	fmt.Println("Debouncer has done signalling")
```

2022-05-11 17:33 UTC, ledongthuc approved these changes

2022-05-12 02:50 UTC, rnvo approved these changes

2022-05-12 03:09 UTC, merged

2022-05-12 03:33 UTC, cuonglm commented
This sounds not right to me. Isn't that multiple calls to Done will hang?